# Generated by Django 3.2.4 on 2021-06-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=45)),
                ('m_name', models.CharField(max_length=45)),
                ('l_name', models.CharField(max_length=45)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('nation', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=45)),
                ('pin_code', models.IntegerField()),
                ('qualification', models.CharField(max_length=45)),
                ('salary', models.IntegerField()),
                ('pan_number', models.CharField(max_length=10)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Response_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField()),
                ('response', models.CharField(max_length=10)),
                ('reason', models.CharField(max_length=45)),
            ],
        ),
    ]
